### ISSUE TITLE
Provide a quit option when right-click icon.

### ISSUE THREAD

**Issue by lmly9193** [rabrain/ai-chat#16]
There's no way to quit application...

**Comment by lilac** [comment]
Thanks for reporting this issue.

Which OS do you use? Is it Windows? If so then this is a known issue, and we're fixing it and hopefully will release it this week.

**Comment by lilac** [comment]
@lmly9193 A [new version](https://github.com/rabrain/ai-chat/releases/tag/v1.2.3) is released just now. It should have fixed the issue you mentioned, please upgrade and verify it works. Thanks again for your feedback.

https://github.com/rabrain/ai-chat/releases/tag/v1.2.3

**Comment by lmly9193** [comment]
Thx for your comment. ❤️
